### ISSUE TITLE
serialize fails in production server

### ISSUE THREAD

**Issue by olanod** [macedigital/silex-jms-serializer-provider#2]
I don't know if its an error in the configuration or in in the jsm serializer it self. When I'm working on my PC the following code returns the json response without problems, but this same call in my heroku prod server returns an empty response(false casted to string).

```
// get articles from database
$articles = $app['em']->getRepository('Shop\Model\Article')->findAll();
// var_dump($articles); // exactly the same in dev and prod servers
//return a json response with the article objects serialized as json 
return new Response(
    (string)$app['serializer']->serialize($articles,'json'),//json array in dev, false in prod
    200,
    ['Content-Type'=>'application/json']
);
```

**Comment by olanod** [comment]
I solved it. Heroku server was using PHP5.5 then I changed it to PHP5.4(like on my PC) and now it works. It is still an issue though, maybe in your code or in the JMS library.

**Comment by macedigital** [comment]
Thanks for the info. I am using PHP v5.5 (local dev-setup and in production) as well, but I didn't notice any regressions. Could you attach a log file, and/or your JMS-Serializer Annotation (or Config-File) so we can get to the bottom of this ?
